### ISSUE TITLE
корректировка в input window with required modules check.

### ISSUE THREAD

**Issue by CunningNobleman** [AlexGameTester/StringSimulation#20]
1) возможно найти другой метод проверки установленных модулей.
2)в self.data нет self.file_picked
3)окно ошибки пустое(нет текста)
4) перепроверить валидацию параметров, перепроверить допустимые интервалы и их корректность
5)добавить в распознавание в случае если файл txt пустой и соответствующее окно ошибки
6)validation further
7)

**Comment by AlexGameTester** [comment]
Fixed all
Number 5 in 1b84aa765d7f01ca4da5b19c196a2aab056e6411
