### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by FrCln** [AlexGameTester/StringSimulation#24]
Нужно создать файл requirements.txt и перечислить в нем используемые библиотеки и их версии. Примерно так:
```
pygame==2.0.0
```
Сейчас мне выдало ошибку
```
ModuleNotFoundError: No module named 'skimage'
```
И вот сиди и думай, чего ему не хватает...

**Comment by FrCln** [comment]
Лучше всего создать виртуальное окружение, установить в него ровно то, что необходимо, убедиться, что все работает, и дать команду:
```
pip freeze > requirements.txt
```

**Comment by AlexGameTester** [comment]
Done 947bd985bdf
