### ISSUE TITLE
Getting Tcl_AsyncDelete error

### ISSUE THREAD

**Issue by FrCln** [AlexGameTester/StringSimulation#25]
При установке параметров по умолчанию после очень быстрого мельтешения шариков на экране программа падает с ошибкой:
```
Tcl_AsyncDelete: async handler deleted by the wrong thread
```

**Comment by FrCln** [comment]
Теперь ошибка выглядит иначе, но она все равно есть. Анимация работает секунд 10, потом начинает заметно тормозить, а потом вылетает вот такая ошибка:
![image](https://user-images.githubusercontent.com/54150197/102023154-8b86ec80-3d9c-11eb-9f28-752b71c73f79.png)
Выходит, он пытается снова обновить progressbar, которого уже давно нет. Но почему только через 10 секунд и почему начинает тормизить? Непонятно. Кстати, это я запускаю на Маке, в прошлый раз запускал на Линуксе.

**Comment by FrCln** [comment]
У вас довольно запутанная структура потока выполнения. Давайте проследим стэк вызовов:
1. При запуске выполняется `manager.start()`
2. Из этой функции вызывается `InputWindow(self)` (само по себе не очень красиво, что конструктор класса тут же начинает какую-то деятельность, но ладно).
3. Он запускает `app.mainloop()`
4. Этот mainloop после нажатия на кнопку Start запускает `self._start`
5. Оттуда запускается `self.manager.start_calculation(params, self._close)` - заметьте, мы до сих пор не вышли из функции `manager.start()` (см. п. 1), мы только все глубже погружаемся в стэк.
6. Отсюда идем в `self._calculations_manager.start_calculation()`
7. Этот стартует два подпроцесса, создает прогрессбар и вызывает у него метод `start`, который опять заходит в очередной `mainloop`. Когда прогрессбар будет закрыт, мы выйдем-таки из функции `start` и вернемся в `calculations_manager.start_calculation`, откуда будет вызвана функция `self._end_calculation()`.
8. Отсюда мы снова вспомним о нашем `manager` (а у него уже запущены две функции, из которых мы тоже никак не выйдем) и запускаем `manager.on_calculation_ended()`. 
9. Далее идем в `self.start_output()`.
10. Оттуда запускаем `self._output_manager.start_animation()`.
11. Оттуда - `self._animation_window.start_animation()`
12. Отсюда, вроде, уже никуда больше не идем, но когда это окно закрывается (в 65 строке файла animation_window.py мы выходим из главного цикла), весь этот стэк начинает разворачиваться в обратную сторону, и мы возвращаемся по очереди во все те функции, которые у нас были запущены. И вот тут-то, очевидно, где-то и возникает проблема. Мы ведь ни из одного mainloop'а не вышли, т.е. все tk-приложения до конца так и не завершились.

В принципе, правильно, что вы сделали некий главный manager, который управляет открытием других окон, но логика его работы должна быть другой - запустили окно, дождались выхода, запускаем следующее. А не так - запустили окно, оно запустило еще одно, то - еще одно и т.д.

**Comment by FrCln** [comment]
Да, и еще в файле animation_window.py вы забыли `pygame.quit()`, поэтому окно в конце не закрывается.

**Comment by AlexGameTester** [comment]
Can't reproduce on Windows 10 & this Linux:
NAME="Linux Mint"
VERSION="19.1 (Tessa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 19.1"
VERSION_ID="19.1"

**Comment by FrCln** [comment]
Да, эта проблема выскакивает только если запускать в интерактивном режиме:
```bash
$ python -i main.py
```
В общем, это, конечно, не очень страшно. Просто немного некрасиво.
