### ISSUE TITLE
Input window autofill

### ISSUE THREAD

**Issue by AlexGameTester** [AlexGameTester/StringSimulation#26]
When you leave some entry field in input window blank and then click 'start', then click 'yes, fill with default parameters', it sets parameters that are outside possible range(1 for precission, for instance) and also raises an exception.

**Comment by CunningNobleman** [comment]
Default values are now : 

5 \ 5  \20 \ 10 
Commit - **Default values**/
https://github.com/AlexGameTester/StringSimulation/commit/356778c219613eb7f704d9b9d3be44a92a3cb439

**Comment by AlexGameTester** [comment]
Fixed. Works in 7c7f1cab75d56952898f8c8b09f94b785551b2c3
