### ISSUE TITLE
Нужно делать issues!!!

### ISSUE THREAD

**Issue by tkhirianov** [AlexGameTester/StringSimulation#6]
Алексей, у вас нет на 52 коммита нет **ни одного** issue!!!!
Нужно делать issues как для багов, так и для улучшений.

**Comment by tkhirianov** [comment]
Ну а теперь почему ничего нет?

**Comment by tkhirianov** [comment]
Вот, например, какую функциональность ты реализовывал в ac100c075e ?
Почему, перед тем, как это делать, ты не завёл никакой issue?
Какое обоснование твоей деятельности?

**Comment by tkhirianov** [comment]
МОжно ссылаться на issue и на pull request-ы через #3

**Comment by AlexGameTester** [comment]
Now there are a lot of issues: #8, #9, #10, #11
