### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by AlexGameTester** [AlexGameTester/StringSimulation#8]
If user doesn't have some required module, e.g. numpy, program should ask him to download it or disable functions that require it

**Comment by CunningNobleman** [comment]
working on it

**Comment by CunningNobleman** [comment]
temporal solution proposed in Branch2 #18

**Comment by AlexGameTester** [comment]
Added requirements.txt 947bd985bdf816ac80382b5fffa531c90d6710a4
